version: "3.7"

services:
  bde_postgres:
    container_name: bde_postgres
    image: postgres
    restart: always
    command:
      - "postgres"
      - "-c"
      - "max_connections=100"
      - "-c"
      - "shared_buffers=2GB"
    env_file:
      - .env
    volumes:
      - ../databases:/docker-entrypoint-initdb.d
      - bde_data:/var/lib/postgresql/data
    networks:
      - bde-isima

  bde_pgadmin:
    container_name: bde_pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8443:443
      - 8080:80
    env_file:
      - .env
    volumes:
      - bde_pgadmin:/var/lib/pgadmin
    networks:
      - bde-isima

volumes:
  bde_data:
  bde_pgadmin:

networks:
  bde-isima:
    external: true